CREATE DATABASE bookstore;
use bookstore;
DROP DATABASE bookstore;
--
CREATE TABLE KHACH_HANG
(
	MAKH VARCHAR(10) NOT NULL,--PRIMARIKEY
	TENKH VARCHAR(20) NOT NULL,
	EMAIL VARCHAR(10),
	SDT VARCHAR(10),
	DIACHI VARCHAR(30),
)
--
CREATE TABLE TAC_GIA
(
	MATG VARCHAR(10) NOT NULL,--PRIMARIKEY
	TENTG VARCHAR(20) NOT NULL,
	QUEQUAN VARCHAR(30) ,
	NAMSINH INT ,
)
--
CREATE TABLE NHAN_VIEN
( 
	MANV VARCHAR(10) NOT NULL,--PRIMARIKEY
	TENNV VARCHAR(20) NOT NULL,
	CHUCVU VARCHAR(10) ,
	CCCD VARCHAR(15),
	LUONG INT,
)
--
CREATE TABLE NHA_XUAT_BAN
(
	MANXB VARCHAR(10) NOT NULL,--PRIMARIKEY
	TENNXB VARCHAR(20) NOT NULL,
	DIACHI VARCHAR(30),
	SDT VARCHAR(10),
)
--
CREATE TABLE NHA_CUNG_CAP
(
	MANCC VARCHAR(10) NOT NULL,--PRIMARIKEY
	TENNCC VARCHAR(20) NOT NULL,
	THONGTIN VARCHAR(50),
)
CREATE TABLE THE_LOAI
(	
	MATL VARCHAR(10) NOT NULL, --PRIMARIKEY
	TENTL VARCHAR(20) NOT NULL,
)
--------- CHẠY OKE
CREATE TABLE SAN_PHAM
( 
	MASP VARCHAR(10) NOT NULL,--PRIMARIKEY
	TENSP VARCHAR(20) NOT NULL,
	SL INT ,
	MATL VARCHAR(10) NOT NULL,
	MATG VARCHAR(10) NOT NULL,
	MANXB VARCHAR(10) NOT NULL,
	NAMXB INT,
	DONGIA INT ,
	SOTRANG INT,
)
--CHAY OKE
CREATE TABLE HOA_DON
(
	MAHD VARCHAR(10) NOT NULL,
	NGAYLAP DATE,
	MANV VARCHAR(10) NOT NULL,
	MAKH VARCHAR(10) NOT NULL,
	TONGTIEN INT,
)
--CHAY OKE
CREATE TABLE CHI_TIET_HOA_DON
(
	MAHD VARCHAR(10) NOT NULL,
	MASP VARCHAR(10) NOT NULL,
	SL INT,
	DONGIA INT,
	THANHTIEN INT,
)
--CHAY OKE
CREATE TABLE CHUONG_TRINH_KHUYEN_MAI
(
	MACTKM VARCHAR(10) NOT NULL,
	NGAYBD DATE,
	NGAYKT DATE,
)
CREATE TABLE KM_THEO_SAN_PHAM
(
	MACTKM  VARCHAR(10) NOT NULL,
	MASP VARCHAR(10) NOT  NULL,
	PHANTRAMKHUYENMAI FLOAT ,
)
CREATE TABLE KM_THEO_HOA_DON
(
	MACTKM VARCHAR(10) NOT NULL,
	SOTIENHOADON INT NOT  NULL,
	PHANTRAMKHUYENMAI FLOAT ,
)
-- CHAY OKE
CREATE TABLE PHIEU_NHAP
(
	MAPN VARCHAR(10) NOT NULL,
	NGAYNHAP DATE,
	MANV VARCHAR(10) NOT NULL,
	MANCC VARCHAR(10) NOT NULL,
	TONGTIEN INT,
)
CREATE TABLE CHI_TIET_PHIEU_NHAP
(
	MAPN VARCHAR(10) NOT NULL,
	MASP VARCHAR(10) NOT NULL,
	DONGIA INT,
	SL INT,
	THANHTIEN INT,
)
--CHAY OKE
--KHOA CHINH
	--
ALTER TABLE KHACH_HANG ADD CONSTRAINT PK_KHACH_HANG PRIMARY KEY (MAKH)
ALTER TABLE NHAN_VIEN ADD CONSTRAINT PK_NHAN_VIEN PRIMARY KEY (MANV)
ALTER TABLE TAC_GIA ADD CONSTRAINT PK_TAC_GIA PRIMARY KEY (MATG)
ALTER TABLE NHA_XUAT_BAN ADD CONSTRAINT PK_NHA_XUAT_BAN PRIMARY KEY (MANXB)
ALTER TABLE NHA_CUNG_CAP ADD CONSTRAINT PK_NHA_CUNG_CAP PRIMARY KEY (MANCC)
--CHAY OKE
	--
ALTER TABLE HOA_DON ADD CONSTRAINT PK_HOA_DON PRIMARY KEY (MAHD)
ALTER TABLE CHI_TIET_HOA_DON ADD CONSTRAINT PK_CHI_TIET_HOA_DON PRIMARY KEY (MAHD,MASP)
ALTER TABLE SAN_PHAM ADD CONSTRAINT PK_SAN_PHAM PRIMARY KEY (MASP)
ALTER TABLE CHUONG_TRINH_KHUYEN_MAI ADD CONSTRAINT PK_CHUONG_TRINH_KHUYEN_MAI PRIMARY KEY (MACTKM)
ALTER TABLE KM_THEO_SAN_PHAM ADD CONSTRAINT PK_KM_THEO_SAN_PHAM PRIMARY KEY (MACTKM,MASP)
ALTER TABLE KM_THEO_HOA_DON ADD CONSTRAINT PK_KM_THEO_HOA_DON PRIMARY KEY (MACTKM,SOTIENHOADON)










